#!/usr/bin/env python3
"""Test Instagram Post with Image"""

import os
import json
import requests
import time
from pathlib import Path
from dotenv import load_dotenv
from datetime import datetime, timezone

load_dotenv()

# Load Instagram credentials
with open("secrets/instagram_token.json", "r") as f:
    ig_creds = json.load(f)

access_token = ig_creds["access_token"]
ig_account_id = ig_creds["business_account_id"]

# Use reliable Unsplash image (tech/success themed)
image_url = "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1080&h=1080&fit=crop&q=80"

caption = f"""🎉 Instagram Integration Complete!

After hours of setup challenges, we've successfully connected @{ig_creds['username']} to the Personal AI Employee system.

Key achievements:
✅ Converted to Business account
✅ Connected to My Test Page
✅ Added as Instagram tester
✅ Generated access token
✅ API access verified

This milestone post is automatically generated by AI to celebrate the completion of Instagram integration for the Gold Tier features.

#PersonalAI #InstagramAPI #Automation #GoldTier #Milestone #BehindTheScenes #TechWin"""

print("=" * 70)
print("Instagram Post Test")
print("=" * 70)
print()
print(f"Account: @{ig_creds['username']}")
print(f"Account ID: {ig_account_id}")
print()
print(f"Image URL: {image_url}")
print()
print("Caption:")
print(caption)
print()
print("=" * 70)
print()

# Step 1: Create media container
print("⏳ Step 1/2: Creating media container...")
url = f"https://graph.instagram.com/v19.0/{ig_account_id}/media"
params = {
    "image_url": image_url,
    "caption": caption,
    "access_token": access_token
}

response = requests.post(url, params=params)

if response.status_code != 200:
    print(f"❌ Error creating media container:")
    print(json.dumps(response.json(), indent=2))
    exit(1)

creation_id = response.json().get("id")
print(f"✅ Media container created: {creation_id}")
print()

# Wait for media to be ready
print("⏳ Waiting 5 seconds for media processing...")
time.sleep(5)
print()

# Step 2: Publish media
print("⏳ Step 2/2: Publishing post to Instagram...")
publish_url = f"https://graph.instagram.com/v19.0/{ig_account_id}/media_publish"
publish_params = {
    "creation_id": creation_id,
    "access_token": access_token
}

publish_response = requests.post(publish_url, params=publish_params)

if publish_response.status_code == 200:
    post_id = publish_response.json().get("id")
    print()
    print("=" * 70)
    print("✅ SUCCESS! Post published to Instagram!")
    print("=" * 70)
    print(f"Post ID: {post_id}")
    print(f"View on Instagram: https://www.instagram.com/p/{post_id}/")
    print()
    
    # Log to audit
    audit_dir = Path("audit_logs")
    audit_dir.mkdir(exist_ok=True)
    
    audit_file = audit_dir / f"audit_{datetime.now().strftime('%Y-%m-%d')}.jsonl"
    audit_entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "action": "instagram_post",
        "post_id": post_id,
        "account_id": ig_account_id,
        "username": ig_creds['username'],
        "caption_length": len(caption),
        "image_url": image_url
    }
    
    with open(audit_file, "a") as f:
        f.write(json.dumps(audit_entry) + "\n")
    
    print("📝 Audit log updated")
    print()
else:
    print(f"❌ Error publishing post:")
    print(json.dumps(publish_response.json(), indent=2))
    print()
